<a href="https://colab.research.google.com/github/RoshanMaharjan7/Concepts-and-Technologies-of-AI/blob/main/Roshan_Maharjan_2408424_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Roshan Maharjan\
Student ID: 2408424

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.\

Problem - 1: Array Creation:

In [1]:
import numpy as np

arr_empty = np.empty((2,2))
print("\n 1. Initialize an empty array with size 2X2.")
print(arr_empty)


print("\n 2. Initialize an all one array with size 4X2.")
print(np.ones((4,2)))

print("\n 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}")
print(np.full((2,2),2))

print("\n 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}")
print(np.zeros_like(arr_empty))

print("\n 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}")
print(np.ones_like(arr_empty))

print("\n 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}")
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("numpy array: ", numpy_array)


 1. Initialize an empty array with size 2X2.
[[ 4.73491001e-310  0.00000000e+000]
 [-3.69602954e+242  6.66507168e-310]]

 2. Initialize an all one array with size 4X2.
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
[[2 2]
 [2 2]]

 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
[[0. 0.]
 [0. 0.]]

 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
[[1. 1.]
 [1. 1.]]

 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
numpy array:  [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [2]:
import numpy as np

print("\n1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.")
new_arr = np.arange(10,50)
print(new_arr)

print("\n2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}")
array2 = np.arange(0,9)
print(array2.reshape(3,3))

print("\n3. Create a 3X3 identity matrix.{Hint:np.eye()}")
array3 = np.eye(3)
print(array3)

print("\n4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}")
array4 = np.random.random(30)
print("Mean = ",array4.mean())

print("\n5. Create a 10X10 array with random values and find the minimum and maximum values.")
array5 = np.random.random((10,10))
print("Min value = ", array5.min())
print("Max value = ", array5.min())

print("\n6. Create a zero array of size 10 and replace 5th element with 1.")
array6 = np.zeros(10)
print("Before replacement")
print(array6)
array6[4] = 1
print("After replacement")
print(array6)

print("\n7. Reverse an array arr = [1,2,0,0,4,0].")
array7 = np.array([1,2,0,0,4,0])
print(array7[::-1])

print("\n8. Create a 2d array with 1 on border and 0 inside.")
array8 = np.ones((4,4))
array8[1:-1, 1:-1] = 0
print(array8)

print("\n9. Create a 8X8 matrix and fill it with a checkerboard pattern.")
array9 = np.zeros((8, 8))
array9[::2, ::2] = 1
array9[1::2, 1::2] = 1
print(array9)


1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Create a 3X3 identity matrix.{Hint:np.eye()}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
Mean =  0.4359850465986888

5. Create a 10X10 array with random values and find the minimum and maximum values.
Min value =  0.011353145437279832
Max value =  0.011353145437279832

6. Create a zero array of size 10 and replace 5th element with 1.
Before replacement
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
After replacement
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reverse an array arr = [1,2,0,0,4,0].
[0 4 0 0 2 1]

8. Create a 2d array with 1 on border and 0 inside.
[[1. 1. 1. 1.

Problem - 3: Array Operations:

In [3]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("\n1. Add the two array.")
add_array = np.add(x,y)
print("Added array = \n",add_array)

print("\n2. Subtract the two array.")
sub_array = np.subtract(v,w)
print("Subtracted array = \n",sub_array)

print("\n3. 3. Multiply the array with any integers of your choice.")
mult_array = np.multiply(2,x)
print("Multiplied array = \n", mult_array)

print("\n4. Find the square of each element of the array.")
square_array = np.power(y,2)
print("Squared array = \n",square_array)

print("\n 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.")
dot_v_w = np.dot(v,w)
dot_x_v = np.dot(x,v)
dot_x_y = np.dot(x,y)

print("Dot product between v and w = \n",dot_v_w)
print("Dot product between x and v = \n",dot_x_v)
print("Dot product between x and y = \n",dot_x_y)


print("\n6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.")
concat_x_y = np.concatenate((x,y), axis=1)
concat_v_w = np.concatenate((v,w), axis=0)
print("Concatenation of x and y along row = \n",concat_x_y)
print("Concatenation of v and w along column = \n",concat_v_w)

print("\n7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?")
print("Ans: We cannot concatenate x and v because x is a 2D array whereas v is 1D array, So, concatenation between array of different dimension is not possible")
concat_x_v = np.concatenate((x,v))
print("Concatenation of x and v = \n",concat_x_v)



1. Add the two array.
Added array = 
 [[ 6  8]
 [10 13]]

2. Subtract the two array.
Subtracted array = 
 [-2 -2]

3. 3. Multiply the array with any integers of your choice.
Multiplied array = 
 [[ 2  4]
 [ 6 10]]

4. Find the square of each element of the array.
Squared array = 
 [[25 36]
 [49 64]]

 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
Dot product between v and w = 
 219
Dot product between x and v = 
 [29 77]
Dot product between x and y = 
 [[19 22]
 [50 58]]

6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
Concatenation of x and y along row = 
 [[1 2 5 6]
 [3 5 7 8]]
Concatenation of v and w along column = 
 [ 9 10 11 12]

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
Ans: We cannot concatenate x and v because x is a 2D array whereas v is 1D array, So, concatenation between array of different dimension is not possible


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

In [5]:
import numpy as np

print("\n 1.Prove A.A-1 = I")
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

A_inverse = np.linalg.inv(A)
A_mul_inverse = np.dot(A, A_inverse);
print(A_mul_inverse)

print("\n 2. Prove AB ̸= BA.")
AB = np.dot(A,B)
BA = np.dot(B,A)
print("AB = \n",AB)
print("BA = \n",BA)
if(np.array_equal(AB,BA)):
  print("AB is equal to BA")
else:
  print("Therefore AB not equal to BA")

print("\n 3. Prove (AB)T = BTAT")
AB_Trans = np.transpose(AB)
B_Trans = np.transpose(B)
A_Trans = np.transpose(A)
BTAT= np.dot(B_Trans, A_Trans)
print("AB Transpose = \n",AB_Trans)
print("BTAT = \n",BTAT)
if(np.array_equal(AB_Trans, BTAT)):
    print("Therefore AB transpose is equal to B transpose A transpose")
else:
    print("They are not equal")



 1.Prove A.A-1 = I
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 2. Prove AB ̸= BA.
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Therefore AB not equal to BA

 3. Prove (AB)T = BTAT
AB Transpose = 
 [[23 51]
 [13 29]]
BTAT = 
 [[23 51]
 [13 29]]
Therefore AB transpose is equal to B transpose A transpose


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1\
x − y + 2z = −3\
3x + y − z = 9\

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [6]:
import numpy as np

A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([[-1],[-2],[9]])

print("A = \n",A)
print("B = \n",B)

A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)
print("The value of X = \n",X)

A = 
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
B = 
 [[-1]
 [-2]
 [ 9]]
The value of X = 
 [[ 2.10526316]
 [ 1.26315789]
 [-1.42105263]]
